  sudo: required
  language: generic 
  services:
    - docker

  before_install:
    - docker build -t itay1989/travissetup -f Dockerfile.dev .

  script:
    - docker run -e CI=true itay1989/travissetup npm run test -- --coverage
    