  sudo: required
  language: generic 
  services:
    - docker

  before_install:
    - docker build -t itay1989/travissetup -f Dockerfile.dev .

  script:
    - docker run -e CI=true itay1989/travissetup npm run test -- --coverage
  
  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-307909669019"
    bucket_path: "docker-react"
    on:
      branch: master
      

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
